version: "3"
name: "lvl-4-project"

services:
  db:
    image: postgres:latest
    ports:
      - "5451:5432" # expose pg on port 5451 to not collide with pg from elswhere
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "allocation-db"
      POSTGRES_HOST_AUTH_METHOD: "trust"

    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - allocation
  postgres_is_ready:
    image: postgres:latest
    networks:
      - allocation
    depends_on:
      db:
        condition: service_healthy
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - allocation

networks:
  allocation:
